### ISSUE TITLE
How many "Proxy IP" are being used?

### ISSUE THREAD

**Issue by LeandroHenriqueSS** [Ethical-H4CK3R/YouTubeViews#6]
Hi

The software is working greatly here. But, I wonder how many "Proxy IP" are being used.

I'm running your software in a few terminals to speed up the views. However, I've noticed that sometimes I'm getting the same proxy on different kali's terminal.

**Comment by Ethical-H4CK3R** [comment]
The IP addresses are unlimited. They have the same IP because they are receiving data through the same port, which is the port that TOR is running on. After a while, one of the terminals will restart TOR and that will force the connections on other terminals to drop, which will force the other terminals to check the connection and request a new IP through the TOR port.
